services:
  - type: web
    name: ielts-materials-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_token_here
